config/routes.rb
Rails.application.routes.draw do
  resources:user do
    resources:genres
    resources:accounts
    resources:account_exchanges
    resources:events
    resources:credits
    post "/events1" => "events#create1"
    post "/events2" => "events#create2"
    post "/events_up1/:id" => "events#update1", as: "events_up1"
    post "/events_up2/:id" => "events#update2", as: "events_up2"
    get "/search" => "events#search"
  end

  devise_for :users, :controllers => {
   :registrations => 'users/registrations',
   :confirmations => 'users/confirmations',
   :sessions => 'users/sessions',
   :passwords => 'users/passwords'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "homepages#home"
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user

  default_scope -> {order(date: :desc)}

  validates :value, presence: true, numericality: { only_integer: true}
  validates :date, presence:true
  validates :genre, presence:true
  validates :account, presence:true
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user

  def index
    form_class
    change_pon
    search_variable
    @events=current_user.events.page(params[:page])
    respond_to do |format|
      format.json { render json: current_user.events }
      format.html {}
    end
  end

  def search
    form_class
    search_variable
    @search=params[:search]
    @iae=params[:iae]

    @date_or_not=params[:date_or_not]
    month1=params["date1(2i)"]
    day1=params["date1(3i)"]
    if (month1=="4" || month1=="6" || month1=="9" || month1=="11") && day1=="31"
      day1="30"
    elsif month1=="2" && (day1.to_i > 28)
      day1=28
    end

    month2=params["date2(2i)"]
    day2=params["date2(3i)"]
    if (month2=="4" || month2=="6" || month2=="9" || month2=="11") && day2=="31"
      day2="30"
    elsif month2=="2" && (day2.to_i > 28)
      day2=28
    end

    if params["date1(1i)"]
      @date1=Date.new(params["date1(1i)"].to_i,month1.to_i,day1.to_i)
      @date2=Date.new(params["date2(1i)"].to_i,month2.to_i,day2.to_i)
    end
    

    @genre=params[:genre]
    @account=params[:account]
    @money_or_not=params[:money_or_not]
    @money1=params[:money1]
    @money2=params[:money2]
    search_event=current_user.events
    if @search!=""
      search_event=search_event.where('memo LIKE ?', "%#{@search}%")
    end
    if @iae!="0"
      if @iae=="false"
        search_event=search_event.where(iae: false)
      else
        search_event=search_event.where(iae: true)
      end
    end
    if @date_or_not=="1"
      search_event=search_event.where('date >= ? and date <= ?', @date1, @date2)
    end
    if @genre!="0"
      search_event=search_event.where(genre: @genre)
    end
    if @account!="0"
      search_event=search_event.where(account: @account)
    end
    if @money_or_not=="1"
      search_event=search_event.where('value >= ? and value <= ?', @money1.to_i, @money2.to_i)
    end
    @events=search_event.page(params[:page])

    @total=0
    search_event.each do |event|
      if event.iae==true
        @total += event.value
      else
        @total -= event.value
      end
    end
    if @date_or_not=="0" || !@date_or_not
      @css1="none"
    else
      @css1="block"
    end
    if @money_or_not=="0" || !@money_or_not
      @css2="none"
    else
      @css2="block"
    end
  end

  def new
    form_class
    new_variable
  end

  def create1
    form_class
    new_variable

    @event=current_user.events.build(events_params)
    if @event.save
      @event.update(iae: false)
      account=Account.find_by(:user_id => current_user.id, :name => @event.account)
      credit=Credit.find_by(:user_id => current_user.id, :name => @event.account)
      if account
        @event.update(pon: true)
        account.update(value: account.value-@event.value)
      elsif credit
        if Account.find_by(:user_id => current_user.id, :name => credit.account)
          a=f_pay_date(@event.date, credit)
          @event.update(pay_date: a, pon: false)
        else
          flash.now[:danger]="選択したクレジットカードと連携しているアカウント(銀行など)が削除されています"
          @event.destroy
          render 'new' and return
        end
      end
      redirect_to user_events_path
    else
      flash.now[:danger]="正しい値を入力してください"
      render "new"
    end
  end

  def create2
    form_class
    new_variable

    @event=current_user.events.build(events_params)
    if @event.save
      @event.update(iae: true, pon: true)
      account=Account.find_by(:user_id => current_user.id, :name => @event.account)
      account.update(value: account.value+@event.value)
      redirect_to user_events_path
    else
      flash.now[:danger]="正しい値を入力してください"
      render "new"
    end
  end

  def destroy
    form_class

    @event=Event.find_by(:user_id => params[:user_id], :id => params[:id])

    before_change_action

    after_change_action

    @event.destroy
    redirect_to user_events_path
  end

  def edit
    form_class
    edit_variable
  end

  def update1
    form_class
    edit_variable

    before_change_action

    a=current_user.events.build(events_params_update1)
    credit=Credit.find_by(:user_id => current_user.id, :name => a.account)
    if credit
      if Account.find_by(:user_id => current_user.id, :name => credit.account)
      else
        flash.now[:danger]="選択したクレジットカードと連携しているアカウント(銀行など)が削除されています"
        render 'edit' and return
      end
    end
    if @event.update(events_params_update1)
      @event.update(iae: false)

      after_change_action

      account=Account.find_by(:user_id => current_user.id, :name => @event.account)
      credit=Credit.find_by(:user_id => current_user.id, :name => @event.account)
      if account
        @event.update(pay_date: nil, pon: true)
        account.update(value: account.value-@event.value)
      elsif credit
        c_account=Account.find_by(:user_id => current_user.id, :name => credit.account)
        if @event.pay_date==nil
          a=f_pay_date(@event.date, credit)
          @event.update(pay_date: a)
        else
          a=Date.new(@event.pay_date.year, @event.pay_date.month, credit.pay_date)
          @event.update(pay_date: a)
        end

        if @event.pay_date <= Date.today
          @event.update(pon: true)
          c_account.update(value: c_account.value-@event.value)
        else
          @event.update(pon: false)
        end
      end
      redirect_to user_events_path
    else
      flash.now[:danger]="正しい値を入力してください"
      render "edit"
    end
  end

  def update2
    form_class
    edit_variable

    before_change_action

    if @event.update(events_params)

      after_change_action

      @event.update(iae: true, pon: true)
      account=Account.find_by(:user_id => current_user.id, :name => @event.account)
      account.update(value: account.value+@event.value)
      redirect_to user_events_path
    else
      flash.now[:danger]="正しい値を入力してください"
      render "edit"
    end
  end

  private
    def correct_user
      @user=User.find(params[:user_id])
      if current_user==@user
      else
        redirect_to root_path
      end
    end

    def events_params
      params.require(:event).permit(:date, :genre, :account, :value, :memo)
    end

    def events_params_update1
      params.require(:event).permit(:date, :genre, :account, :value, :memo, :pay_date)
    end

    def search_variable
      @all_genres=[["すべて","0"]]
      @genres_e=[["すべて","0"]]
      @genres_i=[["すべて","0"]]
      current_user.genres.each do |genre|
        if genre.iae==false
          a=["#{genre.name}", "#{genre.name}"]
          @genres_e.push(a)
        else
          a=["#{genre.name}", "#{genre.name}"]
          @genres_i.push(a)
        end
        a=["#{genre.name}", "#{genre.name}"]
        @all_genres << a
      end

      @accounts_e=[["すべて","0"]]
      current_user.accounts.each do |account|
        a=["#{account.name}", "#{account.name}"]
        @accounts_e.push(a)
      end

      current_user.credits.each do |credit|
        a=["#{credit.name}", "#{credit.name}"]
        @accounts_e << a
      end
    end

    def new_variable
      @credit=false
      @all_genres=[]
      @genres_e=[]
      @genres_i=[]
      current_user.genres.each do |genre|
        if genre.iae==false
          a=["#{genre.name}", "#{genre.name}"]
          @genres_e.push(a)
        else
          a=["#{genre.name}", "#{genre.name}"]
          @genres_i.push(a)
        end
        a=["#{genre.name}", "#{genre.name}"]
        @all_genres << a
      end

      @accounts_e=[]
      @accounts_i=[]
      current_user.accounts.each do |account|
        a=["#{account.name}", "#{account.name}"]
        @accounts_e.push(a)
        @accounts_i.push(a)
      end

      current_user.credits.each do |credit|
        a=["#{credit.name}", "#{credit.name}"]
        @accounts_e << a
      end

      income_recently_genre=current_user.events.where(iae: true).first.genre
      income_recently_account=current_user.events.where(iae: true).first.account
      @income_genre_s=["#{income_recently_genre}", "#{income_recently_genre}"]
      @income_account_s=["#{income_recently_account}", "#{income_recently_account}"]

      expense_recently_genre=current_user.events.where(iae: false).first.genre
      expense_recently_account=current_user.events.where(iae: false).first.account
      @expense_genre_s=["#{expense_recently_genre}", "#{expense_recently_genre}"]
      @expense_account_s=["#{expense_recently_account}", "#{expense_recently_account}"]
    end

    def edit_variable
      @event=Event.find_by(:user_id => params[:user_id], :id => params[:id])
      @credit=Credit.find_by(:user_id => params[:user_id], :name => @event.account)
      @genres_e=[]
      @genres_i=[]
      if @event.iae==true
        @taba=""
        @tabb="active"
      else
        @tabb=""
        @taba="active"
      end
      current_user.genres.each do |genre|
        if genre.iae==false
          a=["#{genre.name}", "#{genre.name}"]
          @genres_e.push(a)
        else
          a=["#{genre.name}", "#{genre.name}"]
          @genres_i.push(a)
        end
      end

      @accounts_e=[]
      @accounts_i=[]
      current_user.accounts.each do |account|
        a=["#{account.name}", "#{account.name}"]
        @accounts_e.push(a)
        @accounts_i.push(a)
      end

      current_user.credits.each do |credit|
        a=["#{credit.name}", "#{credit.name}"]
        @accounts_e << a
      end

      genre=Genre.find_by(:user_id => current_user.id, :name => @event.genre)
      if genre
        @genre_s=["#{genre.name}", "#{genre.name}"]
      else
        flash.now[:danger]="このジャンルは削除されています"
      end

      account=Account.find_by(:user_id => current_user.id, :name => @event.account)
      if account || @credit
        @account_s=["#{@event.account}", "#{@event.account}"]
      else
        flash.now[:danger]="このアカウントまたはクレジットカードは削除されています"
      end
    end

    def before_change_action

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_event_index.html.erb
<div class="table_contents">
  <div class="table-responsive">
    <table class="table" id="table_events">
      <thead>
        <tr>
          <th>日付</th>
          <th>ジャンル</th>
          <th>アカウント</th>
          <th>メモ</th>
          <th>金額</th>
          <th>引き落とし日</th>
          <th></th>
          <th></th>
        </tr>
      </thead>

      <% a=0 %>
      <% @events.each do |event| %>
      <tbody>
        <% if event.iae==false %>
        <tr class="false">
          <% if event.date != a %>
          <td>
            <%= event.date.year %>/<%= event.date.month %>/<%= event.date.day %>
          </td>
          <% else %>
          <td>
          </td>
          <% end %>

          <td><%= event.genre %></td>
          <td><%= event.account %></td>

          <% if event.memo %>
          <td><%= event.memo %></td>
          <% else %>
          <td>
          </td>
          <% end %>

          <td>
            ¥-<%= event.value.to_s(:delimited) %>
          </td>

          <% if event.pay_date %>
          <td>
            <%= "#{event.pay_date.year}/#{event.pay_date.month}/#{event.pay_date.day}" %>
          </td>
          <% else %>
          <td>
          </td>
          <% end %>

          <td>
            <%= link_to "削除", user_event_path(params[:user_id], event.id), method: :DELETE, data: {confirm: "削除してよろしいですか？", "turbolinks" => false} %>
          </td>
          <td>
            <%= link_to "編集", edit_user_event_path(params[:user_id], event.id) %>
          </td>
          <% a=event.date %>
        </tr>
        <% else %>
        <tr class="true">
          <% if event.date != a %>
          <td>
            <%= event.date.year %>/<%= event.date.month %>/<%= event.date.day %>
          </td>
          <% else %>
          <td>
          </td>
          <% end %>

          <td><%= event.genre %></td>
          <td><%= event.account %></td>

          <% if event.memo %>
          <td><%= event.memo %></td>
          <% else %>
          <td>
          </td>
          <% end %>

          <td>
            ¥<%= event.value.to_s(:delimited) %>
          </td>

          <td></td>

          <td>
            <%= link_to "削除", user_event_path(params[:user_id], event.id), method: :DELETE, data: {confirm: "削除してよろしいですか？", "turbolinks" => false} %>
          </td>
          <td>
            <%= link_to "編集", edit_user_event_path(params[:user_id], event.id) %>
          </td>
          <% a=event.date %>
        </tr>
        <% end %>
      </tbody>
      <% end %>
      <%= paginate @events %>
    </table>
  </div>
</div>
<%= paginate @events %>

app/views/events/_event_search.html.erb
<div class="search_column">
  <%= form_with(url: user_search_path(current_user), :method => :get, class: "form1", local: true) do |f| %>
    <div class="iae_search">
      <label>収支を選択してください</label>
      <div class="">
        <%= f.select :iae, [["すべて","0"],["支出",false],["収入",true]], {selected: iae}, class: "form-control", id: "select_js1" %>
      </div>
    </div>

    <div class="date_search">
      <div class="date_or_not">
        <label>日付</label>
        <%= f.select :date_or_not, [["選択しない","0"],["選択する","1"]], {selected: date_or_not},class: "form-control", id: "select_js2" %>
      </div>
      <div class="date_area_<%= css1 %>">
        <label>日付範囲を選択してください</label><br/>
        <%= f.date_select :date1, {start_year:Time.now.year, end_year:1970, selected: date1}, class: "form-control", id: "date_s" %>〜
        <%= f.date_select :date2, {start_year:Time.now.year, end_year:1970, selected: date2}, class: "form-control", id: "date_s" %>
      </div>
    </div>

    <div class="row acount_genre">
      <div class="genre_search col-xs-10 col-xs-offset-1 col-sm-5 col-sm-offset-1" id="all">
        <label>ジャンル</label>
        <%= f.select :genre, @all_genres, {selected: genre}, class: "form-control", id: "select_js4" %>
      </div>

      <div class="account_search col-xs-10 col-xs-offset-1 col-sm-5 col-sm-offset-0">
        <label>アカウント</label>
        <%= f.select :account, @accounts_e, {selected: account}, class: "form-control", id: "select" %>
      </div>

    </div>


    <div class="search-memo">
      <label>メモで検索</label>
      <div class="search_input">
        <%= f.text_field :search, value: search, placeholder: "メモで検索", class: "form-control", id: "name" %>
      </div>
    </div>

    <div class="money_search">
      <div class="money_or_not">
        <label>金額</label>
        <%= f.select :money_or_not, [["選択しない","0"],["選択する","1"]], {selected: money_or_not}, class: "form-control", id: "select_js3" %>
      </div>
      <div class="money_area_<%= css2 %>">
        <label>金額の範囲を入力してください</label><br/>
        <div class="money_inline">
          <%= f.text_field :money1, value: money1, class: "form-control", id: "name" %> 〜
          <%= f.text_field :money2, value: money2, class: "form-control", id: "name" %>
        </div>
      </div>
    </div>

    <div class="search_btn">
      <%= f.submit "検索", class: "btn btn-primary", role: "button" %>
    </div>

  <% end %>
</div>

app/views/events/_form.html.erb
<div class="tab-pane <%= active %>" id="tab_<%= aob %>" role="tabpanel">
  <%= form_for :event, url:url do |f| %>
  <div class="form_wrapper" id="<%= backcolor %>">

    <div class="row">
      <div class="<%= @form_class %>">
        <%= f.label :date, "日付を選択してください", class: "date_label" %>
        <%= f.date_select :date, {selected: date_s}, class: "form-control", id: "date" %>
      </div>
    </div>

    <div class="row">
      <div class="<%= @form_class %>">
        <%= f.label :genre, "ジャンルを選択してください" %>
        <%= f.select :genre, genre,{selected: genre_s}, class: "form-control", id: "select" %>
      </div>
    </div>

    <div class="row">
      <div class="<%= @form_class %>">
        <%= f.label :account, "アカウントを選択してください" %>
        <%= f.select :account, account, {selected: account_s}, class: "form-control", id: "select" %>
      </div>
    </div>

    <div class="row">
      <div class="<%= @form_class %>">
        <%= f.label :memo, "メモ" %>
        <%= f.text_field :memo, value: memo, class: "form-control", id: "text" %>
      </div>
    </div>

    <div class="row">
      <div class="<%= @form_class %>">
        <%= f.label :value, "金額を入力してください" %>
        <%= f.text_field :value, value: money, class: "form-control", id: "value" %>
      </div>
    </div>

    <% if @credit %>
      <div class="row">
        <div class="<%= @form_class %>">
          <%= f.label :pay_date, "引き落とし月を選択してください", class: "date_label" %>
          <%= f.date_select :pay_date, {discard_day:true, selected: @event.pay_date}, class: "form-control", id: "date" %>
        </div>
      </div>
    <% end %>

    <%= f.submit "イベント登録", class: "btn btn-primary", role: "button" %>

  </div>
  <% end %>
</div>

app/views/events/_form_tab.html.erb
<ul class="nav nav-tabs" role="tablist">
  <li class=<%=taba%> role="presentation">
    <a aria-controls="tab_a" data-toggle="tab" href="#tab_a" role="tab">支出</a>
  </li>
  <li class=<%=tabb%> role="presentation">
    <a aria-controls="tab_b" data-toggle="tab" href="#tab_b" role="tab">収入</a>
  </li>
</ul>

app/views/events/edit.html.erb
<h1>イベント編集</h1>
<div>

  <%= render :partial => 'form_tab', :locals => {taba: @taba, tabb: @tabb} %>

  <div class="tab-content">
    <%= render :partial => 'form', :locals => {active: @taba,
                                                aob: "a",
                                                url: user_events_up1_path,
                                                backcolor: "",
                                                date_s: @event.date,
                                                genre: @genres_e,
                                                genre_s: @genre_s,
                                                account: @accounts_e,
                                                account_s: @account_s,
                                                memo: @event.memo,
                                                money: @event.value} %>

    <%= render :partial => 'form', :locals => {active: @tabb,
                                                aob: "b",
                                                url: user_events_up2_path,
                                                backcolor: "income",
                                                date_s: @event.date,
                                                genre: @genres_i,
                                                genre_s: @genre_s,
                                                account: @accounts_i,
                                                account_s: @account_s,
                                                memo: @event.memo,
                                                money: @event.value} %>
  </div>
</div>

app/views/events/index.html.erb
<h1>履歴</h1>
<div class="search-h">検索する</div>
<div class="search_wrapper" id="search_close">
  <%= render :partial => 'event_search', :locals => {search: "",
                                                      iae: "0",
                                                      genre: "0",
                                                      account: "0",
                                                      money1: "",
                                                      money2: "",
                                                      date1: Date.today,
                                                      date2: Date.today,
                                                      date_or_not: "0",
                                                      money_or_not: "0",
                                                      css1: "none",
                                                      css2: "none"} %>
</div>

<%= render "event_index" %>

app/views/events/new.html.erb
<h1>新規イベント作成</h1>
<div>

  <%= render :partial => 'form_tab', :locals => {taba: "active", tabb: ""} %>

  <div class="tab-content">
    <%= render :partial => 'form', :locals => {active: "active",
                                                aob: "a",
                                                url: user_events1_path,
                                                backcolor: "",
                                                date_s: Date.today,
                                                genre: @genres_e,
                                                genre_s: @expense_genre_s,
                                                account: @accounts_e,
                                                account_s: @expense_account_s,
                                                memo: "",
                                                money: ""} %>

    <%= render :partial => 'form', :locals => {active: "",
                                                aob: "b",
                                                url: user_events2_path,
                                                backcolor: "income",
                                                date_s: Date.today,
                                                genre: @genres_i,
                                                genre_s: @income_genre_s,
                                                account: @accounts_i,
                                                account_s: @income_account_s,
                                                memo: "",
                                                money: ""} %>
  </div>
</div>

app/views/events/search.html.erb
<h1>検索結果</h1>
<div class="search-h_const">検索する</div>
<div class="search_wrapper_const" id="search_close">
  <%= render :partial => 'event_search', :locals => {search: @search,
                                                      iae: @iae,
                                                      genre: @genre,
                                                      account: @account,
                                                      money1: @money1,
                                                      money2: @money2,
                                                      date1: @date1,
                                                      date2: @date2,
                                                      date_or_not: @date_or_not,
                                                      money_or_not: @money_or_not,
                                                      css1: @css1,
                                                      css2: @css2} %>
</div>

<%= render "event_index" %>

<div class="search_total">合計収支　¥<%= @total.to_s(:delimited) %></div>