config/routes.rb
Rails.application.routes.draw do
  resources:user do
    resources:genres
    resources:accounts
    resources:account_exchanges
    resources:events
    resources:credits
    post "/events1" => "events#create1"
    post "/events2" => "events#create2"
    post "/events_up1/:id" => "events#update1", as: "events_up1"
    post "/events_up2/:id" => "events#update2", as: "events_up2"
    get "/search" => "events#search"
  end

  devise_for :users, :controllers => {
   :registrations => 'users/registrations',
   :confirmations => 'users/confirmations',
   :sessions => 'users/sessions',
   :passwords => 'users/passwords'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "homepages#home"
end

app/models/credit.rb
class Credit < ApplicationRecord
  belongs_to :user
  validates :name, presence: true, uniqueness: { scope: :user }
  validates :account, presence: true
  validates :pay_date, presence: true,
                       numericality: {
                         only_integer: true,
                         greater_than_or_equal_to: 1,
                         less_than_or_equal_to: 31
                       }
  validates :month_date, presence: true,
                       numericality: {
                         only_integer: true,
                         greater_than_or_equal_to: 1,
                         less_than_or_equal_to: 31
                       }
end

app/controllers/credits_controller.rb
class CreditsController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user

  def index
    form_class
    @credits=current_user.credits
  end

  def new
    form_class
    @credit=current_user.credits.build
    new_variable
  end

  def create
    form_class
    new_variable

    @credit=current_user.credits.build(credits_params)
    if @credit.pay_date==@credit.month_date
      flash[:danger]="締め日と引き落とし日を別日にしてください"
      render "new"
      return
    elsif Account.find_by(:user_id => params[:user_id], :name => @credit.name)
      flash[:danger]="同名のアカウントがあるためクレジットカードの名前を変えてください"
      render "new"
      return
    else
      if @credit.save
        redirect_to user_credits_path
        return
      else
        flash[:danger]="正しい値を入力してください"
        render "new"
        return
      end
    end
  end

  def destroy
    form_class
    @credit=Credit.find_by(:user_id => params[:user_id], :id => params[:id])
    a=true
    current_user.events.each do |event|
      if event.pon==false
        if event.account==@credit.name
          a=false
          break
        end
      end
    end
    current_user.account_exchanges.each do |event|
      if event.pon==false
        if event.bname==@credit.name
          a=false
          break
        end
      end
    end
    if a
      @credit.destroy
      redirect_to user_credits_path
    else
      flash[:danger]="このクレジットカードを使用した未引き落としのイベントまたは振替があるためこのカードは削除できません"
      redirect_to user_credits_path
    end
  end

  def edit
    form_class
    edit_variable
  end

  def update
    form_class
    edit_variable
    events=current_user.events
    c_events=[]
    events.each do |event|
      if event.account==@credit.name
        c_events << event
      end
    end
    a=current_user.credits.build(credits_params)
    if a.pay_date==a.month_date
      flash[:danger]="締め日と引き落とし日を別日にしてください"
      render "edit"
    elsif Account.find_by(:user_id => params[:user_id], :name => a.name)
      flash[:danger]="同名のアカウントがあるためクレジットカードの名前を変えてください"
      render "edit"
    else
      if @credit.update(credits_params)
        c_events.each do |event|
          c_account=Account.find_by(:user_id => current_user.id, :name => @credit.account)
          a=f_pay_date(event.date, @credit)
          if event.pon==true
            c_account.update(value: c_account.value+event.value)
          end
          if a>Date.today
            event.update(account: @credit.name, pon: false, pay_date: a)
          else
            event.update(account: @credit.name, pon: true, pay_date: a)
            c_account.update(value: c_account.value-event.value)
          end
        end
        redirect_to user_credits_path
      else
        flash[:danger]="正しい値を入力してください"
        render "new"
      end
    end
  end

  def show
    form_class
    @accounts=current_user.accounts
    @credit=Credit.find_by(:user_id => params[:user_id], :id => params[:id])
    today=Date.today

    change_pon

    @not_pay=[]
    not_pay_month=Hash.new
    a=0
    b=0
    @events.each do |event|
      if event.pon==false
        if event.account==@credit.name
          if a != event.pay_date.month || b != event.pay_date.year
            if not_pay_month != {}
              @not_pay << not_pay_month
            end

            # Hashの初期化
            not_pay_month=Hash.new
            not_pay_month[:date]=event.pay_date
            not_pay_month[:event]=[]
            not_pay_month[:ac_ex]=[]
            not_pay_month[:total]=0
          end

          not_pay_month[:event] << event
          not_pay_month[:total] += event.value

          a=event.pay_date.month
          b=event.pay_date.year
        end
      end
    end
    if not_pay_month != {}
      @not_pay << not_pay_month
    end

    a=0
    b=0
    not_pay_hash=Hash.new
    @account_exchanges.each do |ac_ex|
      if ac_ex.pon==false
        if ac_ex.bname==@credit.name
          foo=true
          @not_pay.each do |not_pay_month|
            if ac_ex.pay_date==not_pay_month[:date]
              not_pay_month[:total] += ac_ex.value
              not_pay_month[:ac_ex] << ac_ex
              foo=false
              break
            end
          end

          if foo==false
            next
          end

          if a != ac_ex.pay_date.month || b != ac_ex.pay_date.year
            if not_pay_hash != {}
              @not_pay << not_pay_hash
            end
            # hashの初期化
            not_pay_hash=Hash.new
            not_pay_hash[:date]=ac_ex.pay_date
            not_pay_hash[:event]=[]
            not_pay_hash[:ac_ex]=[]
            not_pay_hash[:total]=0
          end

          not_pay_hash[:total] += ac_ex.value
          not_pay_hash[:ac_ex] << ac_ex

          a=ac_ex.pay_date.month
          a=ac_ex.pay_date.year
        end
      end
    end
    if not_pay_hash != {}
      @not_pay << not_pay_hash
    end
  end

  private
    def correct_user
      @user=User.find(params[:user_id])
      if current_user==@user
      else
        redirect_to root_path
      end
    end

    def credits_params
      params.require(:credit).permit(:name, :account, :pay_date, :month_date)
    end

    def new_variable
      @accounts=[]
      current_user.accounts.each do |account|
        a=["#{account.name}", "#{account.name}"]
        @accounts << a
      end

      @days=[]
      (1..31).each do |day|
        a=["#{day}", "#{day}"]
        @days << a
      end
    end

    def edit_variable
      @credit=Credit.find_by(:user_id => params[:user_id], :id => params[:id])
      @accounts=[]
      current_user.accounts.each do |account|
        a=["#{account.name}", "#{account.name}"]
        @accounts << a
      end

      account=Account.find_by(:user_id => current_user.id, :name => @credit.account)
      if account
        @account=["#{account.name}", "#{account.name}"]
      else
        flash[:danger]="連携アカウントは削除されています"
      end

      @days=[]
      (1..31).each do |day|
        a=["#{day}", "#{day}"]
        @days << a
      end
    end
end

app/helpers/credits_helper.rb
module CreditsHelper
end

app/views/credits/_form.html.erb
<%= form_for :credit, url:url, method: method do |f| %>
<div class="form_wrapper">
  <div class="row">
    <div class="<%= @form_class %>">
      <%= f.label :name, "カードの名前を入力してください" %>
      <%= f.text_field :name, value: name, class: "form-control", id: "name" %>
    </div>
  </div>

  <div class="row">
    <div class="<%= @form_class %>">
      <%= f.label :account, "引き落とし先のアカウントを選択してください" %>
      <%= f.select :account, @accounts, {selected: account}, class: "form-control", id: "select" %>
    </div>
  </div>

  <div class="row">
    <div class="<%= @form_class %>">
      <%= f.label :pay_date, "引き落とし日を選択してください", class: "date_label" %>
      <%= f.select :pay_date, @days, {selected: day1}, class: "form-control", id: "day_select" %>
    </div>
  </div>

  <div class="row">
    <div class="<%= @form_class %>">
      <%= f.label :month_date, "締め日を選択してください", class: "date_label" %>
      <%= f.select :month_date, @days, {selected: day2}, class: "form-control", id: "day_select" %>
    </div>
  </div>

  <%= f.submit "クレジットカード登録", class: "btn btn-primary", role: "button" %>
</div>

<% end %>

app/views/credits/edit.html.erb
<h1>クレジットカード情報編集</h1>

<%= render partial: "form" , :locals => {url: user_credit_path, method: :put, name: @credit.name, account: @account, day1: @credit.pay_date, day2: @credit.month_date} %>

app/views/credits/index.html.erb
<h1>クレジットカード一覧</h1>

<div class="account">
  <p>こちらではクレジットカードの登録<br/>(連携アカウント、締め日、引き落とし日の登録)ができます。</p>
  <div class="new_account">
    <li><%= link_to "クレジットカード作成", new_user_credit_path %></li>
  </div>
</div>

<div class="row">
  <div class="table_contents col-xs-12 col-sm-offset-2 col-sm-8">
    <div class="table-responsive">
      <table class="table" id="table_accounts">
        <thead>
          <tr>
            <th>名前</th>
            <th>引き落とし先アカウント</th>
            <th>引き落とし日</th>
            <th>締め日</th>
            <th></th>
            <th></th>
            <th></th>
          </tr>
        </thead>

        <% @credits.each do |credit| %>

        <tbody>
          <tr>
            <td><%=credit.name %></td>
            <td><%= credit.account %></td>
            <td><%= credit.pay_date %></td>
            <td><%= credit.month_date %></td>
            <td><%=link_to "詳細", user_credit_path(params[:user_id], :id => credit.id) %></td>
            <td><%=link_to "削除", user_credit_path(params[:user_id], :id => credit.id), method: :DELETE, data: {confirm: "削除してよろしいですか？", "turbolinks" => false} %></td>
            <td><%=link_to "編集", edit_user_credit_path(params[:user_id], :id => credit.id) %></td>
          </tr>
        </tbody>

        <% end %>

      </table>
    </div>
  </div>
</div>

app/views/credits/new.html.erb
<h1>新規クレジットカード作成</h1>

<%= render partial: "form" , :locals => {url: user_credits_path, method: :post, name: "", account: "", day1: "", day2: ""} %>

app/views/credits/show.html.erb
<h1><%= @credit.name %></h1>

<% if @not_pay != [] %>
  <p class="explanation"><%= @credit.name %>での未引き落としのイベントは以下です</p>
  <% @not_pay.each do |not_pay_month| %>
      <h2 class="credit-title">引き落とし日　<%= not_pay_month[:date].year %>/<%= not_pay_month[:date].month %>/<%= not_pay_month[:date].day %></h2>
      <p class="explanation2">合計で¥<%= not_pay_month[:total].to_s(:delimited) %>引き落とされます</p>
      <div class="table_contents row">
        <div class="table-responsive col-xs-12 col-md-6">
          <table class="table" id="table_accounts">
            <caption>
              イベント
            </caption>
            <thead>
              <tr>
                <th>日付</th>
                <th>ジャンル</th>
                <th>メモ</th>
                <th>金額</th>
              </tr>
            </thead>

            <% if not_pay_month[:event] != [] %>

            <% not_pay_month[:event].each do |not_pay_event| %>

            <tbody>
              <tr>
                <td><%= not_pay_event.date.year %>/<%= not_pay_event.date.month %>/<%= not_pay_event.date.day %></td>
                <td><%= not_pay_event.genre %></td>
                <td><%= not_pay_event.memo %></td>
                <td>¥<%= not_pay_event.value.to_s(:delimited) %></td>
              </tr>
            </tbody>
            <% end %>

            <% end %>
          </table>
          <% if not_pay_month[:event] == [] %>
            <p>イベントで未引き落としのものはありません</p>
          <% end %>
        </div>

        <div class="table-responsive col-xs-12 col-md-6">
          <table class="table" id="table_accounts">
            <caption>
              振替
            </caption>
            <thead>
              <tr>
                <th>日付</th>
                <th>振替先アカウント</th>
                <th>金額</th>
              </tr>
            </thead>

            <% if not_pay_month[:ac_ex] != [] %>

            <% not_pay_month[:ac_ex].each do |not_pay_ac| %>

            <tbody>
              <tr>
                <td><%= not_pay_ac.date.year %>/<%= not_pay_ac.date.month %>/<%= not_pay_ac.date.day %></td>
                <td><%= not_pay_ac.aname %></td>
                <td>¥<%= not_pay_ac.value.to_s(:delimited) %></td>
              </tr>
            </tbody>
            <% end %>

            <% end %>
          </table>
          <% if not_pay_month[:ac_ex] == [] %>
            <p>振替で未引き落としのものはありません</p>
          <% end %>
        </div>
    </div>
  <% end %>
<% else %>
  <p>このクレジットカードを使用した未引き落としイベントはありません</p>
<% end %>