config/routes.rb
Rails.application.routes.draw do
  resources:user do
    resources:genres
    resources:accounts
    resources:account_exchanges
    resources:events
    resources:credits
    post "/events1" => "events#create1"
    post "/events2" => "events#create2"
    post "/events_up1/:id" => "events#update1", as: "events_up1"
    post "/events_up2/:id" => "events#update2", as: "events_up2"
    get "/search" => "events#search"
  end

  devise_for :users, :controllers => {
   :registrations => 'users/registrations',
   :confirmations => 'users/confirmations',
   :sessions => 'users/sessions',
   :passwords => 'users/passwords'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "homepages#home"
end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :user

  default_scope -> {order(value: :desc)}

  validates :name, presence: true, uniqueness: { scope: :user }
  validates :value, presence: true, numericality: { only_integer: true}
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user

  def index
    form_class
    @total=0

    @accounts=current_user.accounts
    @genres=current_user.genres

    change_pon

    # total残高求める
    @accounts.each do |account|
      @total=@total+account.value
    end

    # 引き落とし後の残高を求める
    @accounts_after=[]
    @accounts.each do |account|
      after_value=account.value
      a=[account.name]
      @events.each do |event|
        if event.pon==false
          credit=Credit.find_by(:user_id => current_user.id, :name => event.account)
          if credit
            c_account=Account.find_by(:user_id => current_user.id, :name => credit.account)
            if c_account==account
              after_value -= event.value
            end
          end
        end
      end
      @account_exchanges.each do |event|
        if event.pon==false
          credit=Credit.find_by(:user_id => current_user.id, :name => event.bname)
          if credit
            c_account=Account.find_by(:user_id => current_user.id, :name => credit.account)
            if c_account==account
              after_value -= event.value
            end
          end
        end
      end
      a << after_value
      @accounts_after << a
    end

    @total_after=0
    @accounts_after.each do |account_after|
      @total_after += account_after[1]
    end

    # アカウント別引き落とし後の残高
    @accounts_all=[]
    @accounts.each do |account|
      a=[account.id, account.name, account.value]
      @accounts_after.each do |account_after|
        if account_after[0]==account.name
          a << account_after[1]
        end
      end
      @accounts_all << a
    end


    # ジャンルの順番変える
    @genres_array_e=[]
    @genres_array_i=[]
    @genres.each do |genre|
      if genre.iae==false
        @genres_array_e << genre.name
      else
        @genres_array_i << genre.name
      end
    end

    # 月ごとの収支
    a=0
    b=0
    @month_pm=Array.new
    month_pm_genre=Hash.new

    @events.each do |event|
      if a != event.date.month || b != event.date.year

        if month_pm_genre != {}
          @month_pm << month_pm_genre
        end

        # Hashの初期化
        month_pm_genre=Hash.new
        month_pm_genre[:year]=event.date.year
        month_pm_genre[:month]=event.date.month
        month_pm_genre[:pm]=0
        month_pm_genre[:in]=0
        month_pm_genre[:out]=0
        @genres.each do |genre|
          month_pm_genre[genre.name]=0
        end
      end

      if event.iae==false
        month_pm_genre[:pm] -= event.value
        month_pm_genre[:out] += event.value
      else
        month_pm_genre[:pm] += event.value
        month_pm_genre[:in] += event.value
      end

      @genres.each do |genre|
        if genre.name==event.genre
          a=month_pm_genre[genre.name]
          if genre.iae==false
            a -= event.value
          else
            a += event.value
          end
          month_pm_genre[genre.name]=a
        end
      end

      a=event.date.month
      b=event.date.year
    end
    @month_pm << month_pm_genre
    @month_pm_paginate=Kaminari.paginate_array(@month_pm).page(params[:month]).per(5)

    # 年ごとの収支
    a=0
    @year_pm=Array.new
    year_pm_genre=Hash.new

    @events.each do |event|
      if a!=event.date.year

        if year_pm_genre != {}
          @year_pm << year_pm_genre
        end

        # Hashの初期化
        year_pm_genre=Hash.new
        year_pm_genre[:year]=event.date.year
        year_pm_genre[:pm]=0
        year_pm_genre[:in]=0
        year_pm_genre[:out]=0
        @genres.each do |genre|
          year_pm_genre[genre.name]=0
        end
      end

      if event.iae==false
        year_pm_genre[:pm] -= event.value
        year_pm_genre[:out] += event.value
      else
        year_pm_genre[:pm] += event.value
        year_pm_genre[:in] += event.value
      end

      @genres.each do |genre|
        if genre.name==event.genre
          a=year_pm_genre[genre.name]
          if genre.iae==false
            a -= event.value
          else
            a += event.value
          end
          year_pm_genre[genre.name]=a
        end
      end

      a=event.date.year
    end
    @year_pm << year_pm_genre
    @year_pm_paginate=Kaminari.paginate_array(@year_pm).page(params[:year]).per(3)

  end

  def new
    @account=current_user.accounts.build
    form_class
  end

  def create
    form_class
    @account=current_user.accounts.build(accounts_params)
    if @account.save
      redirect_to user_accounts_path
    else
      flash[:danger]="正しい値を入力してください"
      render "new"
    end
  end

  def destroy
    form_class
    @account=Account.find_by(:user_id => params[:user_id], :id => params[:id])
    a=true
    current_user.credits.each do |credit|
      if credit.account==@account.name
        a=false
        break
      end
    end
    if a
      @account.destroy
    else
      flash[:danger]="このアカウントに連携したクレジットカードが存在するためこのアカウントは削除できません"
      redirect_to user_accounts_path and return
    end
    redirect_to user_accounts_path
  end

  private
    def correct_user
      @user=User.find(params[:user_id])
      if current_user==@user
      else
        redirect_to root_path
      end
    end

    def accounts_params
      params.require(:account).permit(:name, :value)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/index.html.erb
<h1>統計情報</h1>

<div class="account">
  <% if current_user.accounts==[] %>
  <p>まずはこちらからアカウント(銀行、現金、電子マネーなど)を追加しましょう。</p>
  <% end %>
  <div class="new_account">
    <li><%= link_to "アカウント追加", new_user_account_path %></li>
  </div>
  <div class="account_exchange">
    <li><%= link_to "新規振替", new_user_account_exchange_path %></li>
    <li><%= link_to "振替履歴", user_account_exchanges_path %></li>
    <p>こちらではアカウント間のお金の移動ができます。</p>
  </div>
</div>

<div class="row">
  <div class="col-xs-12 col-sm-6">
    <h2>残高</h2>
    <div class="table_contents">
      <div class="table-responsive">
        <table class="table" id="table_accounts">
          <thead>
            <tr>
              <th>現在残高</th>
              <th>引き落とし後の残高</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>¥<%= @total.to_s(:delimited) %></td>
              <td>¥<%= @total_after.to_s(:delimited) %></td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>

  <div class="col-xs-12 col-sm-6">
    <h2>アカウント残高</h2>

    <div class="table_contents">
      <div class="table-responsive">
        <table class="table" id="table_accounts">
          <thead>
            <tr>
              <th>アカウント</th>
              <th>金額</th>
              <th>引き落とし後の金額</th>
              <th></th>
            </tr>
          </thead>

          <% @accounts_all.each do |account_all| %>

          <tbody>
            <tr>
              <td><%= account_all[1] %></td>
              <td>¥<%= account_all[2].to_s(:delimited) %></td>
              <td>¥<%= account_all[3].to_s(:delimited) %></td>
              <td><%= link_to "削除", user_account_path(params[:user_id], account_all[0]), method: :DELETE, data: {confirm: "削除してよろしいですか？", "turbolinks" => false} %></td>
            </tr>
          </tbody>

          <% end %>

        </table>
      </div>
    </div>
  </div>
</div>

<h2>月ごとの収支</h2>

<% if @events!=[] %>

<div class="table_contents">
  <div class="table-responsive">
    <table class="table" id="pm">
      <thead>
        <tr>
          <th>年</th>
          <th class="border-right">月</th>
          <th>収入</th>
          <th class="border-right">支出</th>
          <th>収支</th>
        </tr>
      </thead>

      <% a=0 %>
      <% @month_pm_paginate.each do |month_pm_genre| %>

      <tbody>
        <tr>
          <% if a != month_pm_genre[:year] %>
          <td><%= month_pm_genre[:year] %>年</td>
          <% else %>
          <td></td>
          <% end %>

          <td class="border-right"><%= month_pm_genre[:month] %>月</td>
          <td>¥<%= month_pm_genre[:in].to_s(:delimited) %></td>
          <td class="border-right">¥-<%= month_pm_genre[:out].to_s(:delimited) %></td>
          <td>¥<%= month_pm_genre[:pm].to_s(:delimited) %></td>
        </tr>
      </tbody>

      <% a=month_pm_genre[:year] %>
      <% end %>

      <%= paginate @month_pm_paginate, param_name: 'month' %>
    </table>
  </div>
</div>

<% else %>

<p>まだイベントがありません</p>
<% end %>

<h2>年ごとの収支</h2>
<% if @events!=[] %>
<div class="table_contents">
  <div class="table-responsive">
    <table class="table" id="pm">
      <thead>
        <tr>
          <th class="border-right">年</th>
          <th>収入</th>
          <th class="border-right">支出</th>
          <th>収支</th>
        </tr>
      </thead>

      <% @year_pm_paginate.each do |year_pm_genre| %>
      <tbody>
        <tr>
          <td class="border-right"><%= year_pm_genre[:year] %>年</td>
          <td>¥<%= year_pm_genre[:in].to_s(:delimited) %></td>
          <td class="border-right">¥-<%= year_pm_genre[:out].to_s(:delimited) %></td>
          <td>¥<%= year_pm_genre[:pm].to_s(:delimited) %></td>
        </tr>
      </tbody>

      <% end %>
      <%= paginate @year_pm_paginate, param_name: 'year' %>
    </table>
  </div>

</div>

<% else %>

<p>まだイベントがありません</p>

<% end %>

app/views/accounts/new.html.erb
<h1>新規アカウント作成</h1>
<%= form_for :account, url:user_accounts_path do |f| %>

<div class="form_wrapper">

  <div class="row">
    <div class='<%= @form_class %>'>
      <%= f.label :name, "名前を入力してください" %>
      <%= f.text_field :name, class: "form-control", id: "name" %>
    </div>
  </div>

  <div class="row">
    <div class="<%= @form_class %>">
      <%= f.label :value, "初期値を入力してください" %>
      <%= f.text_field :value, class: "form-control", id: "value" %>
    </div>
  </div>

  <%= f.submit "アカウント作成", class: "btn btn-primary", role: "button" %>
</div>

<% end %>